### ISSUE TITLE
Using Switch-Case instead of Else..If

### ISSUE THREAD

**Issue by debiprasadmishra50** [Rapid-learnings/nestjs-secrets-manager#1]
if (error) {
      if (error.code === "DecryptionFailureException")
        // Secrets Manager can't decrypt the protected secret text using the provided KMS key.
        // Deal with the exception here, and/or rethrow at your discretion.
        throw error;
      else if (error.code === "InternalServiceErrorException")
        // An error occurred on the server side.
        // Deal with the exception here, and/or rethrow at your discretion.
        throw error;
      else if (error.code === "InvalidParameterException")
        // You provided an invalid value for a parameter.
        // Deal with the exception here, and/or rethrow at your discretion.
        throw error;
      else if (error.code === "InvalidRequestException")
        // You provided a parameter value that is not valid for the current state of the resource.
        // Deal with the exception here, and/or rethrow at your discretion.
        throw error;
      else if (error.code === "ResourceNotFoundException")
        // We can't find the resource that you asked for.
        // Deal with the exception here, and/or rethrow at your discretion.
        throw error;
    }

**Comment by ArunDavidRapidInnovations** [comment]
Fixed in commit d616484af6138461a2e84e4b51cf013418829560 

All the cases just throw errors. so just commented out the entire switch statement. people can un-commit it if they want to handle a specific case separately.
