### ISSUE TITLE
Maintaining url-path format, either with "/" or without

### ISSUE THREAD

**Issue by debiprasadmishra50** [Rapid-learnings/nestjs-secrets-manager#3]
@Get('/firstPhrase')
  async getFirstPhrase(): Promise<string> {
    return await this.configService.get('PORT');
  }

  @Get('secondPhrase')
  async getSecondPhrase(): Promise<string> {
    return await this.configService.get('SOME_VAL');
  }

**Comment by ArunDavidRapidInnovations** [comment]
Fixed in commit fe8c35de2f13cc33a68f78398f19c7a38a671618
