### ISSUE TITLE
Removing Hello World Code

### ISSUE THREAD

**Issue by debiprasadmishra50** [Rapid-learnings/nestjs-secrets-manager#4]
@Get()
  getHello(): string {
    return this.appService.getHello();
  }
 -------------------------------------------------------------------------------
  import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getHello(): string {
    return 'Hello World!';
  }
}

**Comment by ArunDavidRapidInnovations** [comment]
Fixed in commit 6daaa8aa6cf3700b0325e04269fe74b8912a2337.
