### ISSUE TITLE
Creating getter and setters for private variables by following Encapsulation SOP

### ISSUE THREAD

**Issue by debiprasadmishra50** [Rapid-learnings/nestjs-secrets-manager#5]
private readonly region = this.configService.get("AWS_REGION")
    ? this.configService.get("AWS_REGION")
    : "YOUR_AWS_REGION";
  private readonly secretName = this.configService.get("AWS_SECRET_NAME")
    ? this.configService.get("AWS_SECRET_NAME")
    : "YOUR_AWS_AWS_SECRET_NAME";
  private readAWSConfig = true;
  private envConfig = {};

**Comment by ArunDavidRapidInnovations** [comment]
As non of the private variables created are supposed to be used outside this file I don't think there is any need to have getters and setters for them here. 

I might be wrong, 

will keep this issue open for any comment from @abhijeet-sonaje before closing it.

**Comment by debiprasadmishra50** [comment]
@abhijeet-sonaje Please make suggestions on this issue

**Comment by abhijeet-sonaje** [comment]
there are few changes that we need to do.... @tapasthakkar will be raising other PR for changes on this one...

**Comment by debiprasadmishra50** [comment]
In that case, we can close this issue. @ArunDavidRapidInnovations
